// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RichMan.proto

package com.demo.netty.protobuf.personinfo.pojo;

public final class RichManProto {
  private RichManProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface RichManOrBuilder extends
      // @@protoc_insertion_point(interface_extends:netty.RichMan)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 id = 1;</code>
     */
    int getId();

    /**
     * <code>string name = 2;</code>
     */
    java.lang.String getName();
    /**
     * <code>string name = 2;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>string email = 3;</code>
     */
    java.lang.String getEmail();
    /**
     * <code>string email = 3;</code>
     */
    com.google.protobuf.ByteString
        getEmailBytes();

    /**
     * <code>repeated .netty.RichMan.Car cars = 4;</code>
     */
    java.util.List<com.demo.netty.protobuf.personinfo.pojo.RichManProto.RichMan.Car>
        getCarsList();
    /**
     * <code>repeated .netty.RichMan.Car cars = 4;</code>
     */
    com.demo.netty.protobuf.personinfo.pojo.RichManProto.RichMan.Car getCars(int index);
    /**
     * <code>repeated .netty.RichMan.Car cars = 4;</code>
     */
    int getCarsCount();
    /**
     * <code>repeated .netty.RichMan.Car cars = 4;</code>
     */
    java.util.List<? extends com.demo.netty.protobuf.personinfo.pojo.RichManProto.RichMan.CarOrBuilder>
        getCarsOrBuilderList();
    /**
     * <code>repeated .netty.RichMan.Car cars = 4;</code>
     */
    com.demo.netty.protobuf.personinfo.pojo.RichManProto.RichMan.CarOrBuilder getCarsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code netty.RichMan}
   */
  public  static final class RichMan extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:netty.RichMan)
      RichManOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use RichMan.newBuilder() to construct.
    private RichMan(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RichMan() {
      name_ = "";
      email_ = "";
      cars_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private RichMan(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              id_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              email_ = s;
              break;
            }
            case 34: {
              if (!((mutable_bitField0_ & 0x00000008) != 0)) {
                cars_ = new java.util.ArrayList<com.demo.netty.protobuf.personinfo.pojo.RichManProto.RichMan.Car>();
                mutable_bitField0_ |= 0x00000008;
              }
              cars_.add(
                  input.readMessage(com.demo.netty.protobuf.personinfo.pojo.RichManProto.RichMan.Car.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000008) != 0)) {
          cars_ = java.util.Collections.unmodifiableList(cars_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.demo.netty.protobuf.personinfo.pojo.RichManProto.internal_static_netty_RichMan_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.demo.netty.protobuf.personinfo.pojo.RichManProto.internal_static_netty_RichMan_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.demo.netty.protobuf.personinfo.pojo.RichManProto.RichMan.class, com.demo.netty.protobuf.personinfo.pojo.RichManProto.RichMan.Builder.class);
    }

    /**
     * Protobuf enum {@code netty.RichMan.CarBrand}
     */
    public enum CarBrand
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>BENZ = 0;</code>
       */
      BENZ(0),
      /**
       * <code>LAMBORGHINI = 1;</code>
       */
      LAMBORGHINI(1),
      /**
       * <code>PORSCHE = 2;</code>
       */
      PORSCHE(2),
      /**
       * <code>AUQI = 3;</code>
       */
      AUQI(3),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>BENZ = 0;</code>
       */
      public static final int BENZ_VALUE = 0;
      /**
       * <code>LAMBORGHINI = 1;</code>
       */
      public static final int LAMBORGHINI_VALUE = 1;
      /**
       * <code>PORSCHE = 2;</code>
       */
      public static final int PORSCHE_VALUE = 2;
      /**
       * <code>AUQI = 3;</code>
       */
      public static final int AUQI_VALUE = 3;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static CarBrand valueOf(int value) {
        return forNumber(value);
      }

      public static CarBrand forNumber(int value) {
        switch (value) {
          case 0: return BENZ;
          case 1: return LAMBORGHINI;
          case 2: return PORSCHE;
          case 3: return AUQI;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<CarBrand>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          CarBrand> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<CarBrand>() {
              public CarBrand findValueByNumber(int number) {
                return CarBrand.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.demo.netty.protobuf.personinfo.pojo.RichManProto.RichMan.getDescriptor().getEnumTypes().get(0);
      }

      private static final CarBrand[] VALUES = values();

      public static CarBrand valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private CarBrand(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:netty.RichMan.CarBrand)
    }

    public interface CarOrBuilder extends
        // @@protoc_insertion_point(interface_extends:netty.RichMan.Car)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>.netty.RichMan.CarBrand brand = 1;</code>
       */
      int getBrandValue();
      /**
       * <code>.netty.RichMan.CarBrand brand = 1;</code>
       */
      com.demo.netty.protobuf.personinfo.pojo.RichManProto.RichMan.CarBrand getBrand();

      /**
       * <code>string name = 2;</code>
       */
      java.lang.String getName();
      /**
       * <code>string name = 2;</code>
       */
      com.google.protobuf.ByteString
          getNameBytes();
    }
    /**
     * Protobuf type {@code netty.RichMan.Car}
     */
    public  static final class Car extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:netty.RichMan.Car)
        CarOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use Car.newBuilder() to construct.
      private Car(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private Car() {
        brand_ = 0;
        name_ = "";
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private Car(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                int rawValue = input.readEnum();

                brand_ = rawValue;
                break;
              }
              case 18: {
                java.lang.String s = input.readStringRequireUtf8();

                name_ = s;
                break;
              }
              default: {
                if (!parseUnknownField(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.demo.netty.protobuf.personinfo.pojo.RichManProto.internal_static_netty_RichMan_Car_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.demo.netty.protobuf.personinfo.pojo.RichManProto.internal_static_netty_RichMan_Car_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.demo.netty.protobuf.personinfo.pojo.RichManProto.RichMan.Car.class, com.demo.netty.protobuf.personinfo.pojo.RichManProto.RichMan.Car.Builder.class);
      }

      public static final int BRAND_FIELD_NUMBER = 1;
      private int brand_;
      /**
       * <code>.netty.RichMan.CarBrand brand = 1;</code>
       */
      public int getBrandValue() {
        return brand_;
      }
      /**
       * <code>.netty.RichMan.CarBrand brand = 1;</code>
       */
      public com.demo.netty.protobuf.personinfo.pojo.RichManProto.RichMan.CarBrand getBrand() {
        @SuppressWarnings("deprecation")
        com.demo.netty.protobuf.personinfo.pojo.RichManProto.RichMan.CarBrand result = com.demo.netty.protobuf.personinfo.pojo.RichManProto.RichMan.CarBrand.valueOf(brand_);
        return result == null ? com.demo.netty.protobuf.personinfo.pojo.RichManProto.RichMan.CarBrand.UNRECOGNIZED : result;
      }

      public static final int NAME_FIELD_NUMBER = 2;
      private volatile java.lang.Object name_;
      /**
       * <code>string name = 2;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        }
      }
      /**
       * <code>string name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      private byte memoizedIsInitialized = -1;
      @java.lang.Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      @java.lang.Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (brand_ != com.demo.netty.protobuf.personinfo.pojo.RichManProto.RichMan.CarBrand.BENZ.getNumber()) {
          output.writeEnum(1, brand_);
        }
        if (!getNameBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
        }
        unknownFields.writeTo(output);
      }

      @java.lang.Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (brand_ != com.demo.netty.protobuf.personinfo.pojo.RichManProto.RichMan.CarBrand.BENZ.getNumber()) {
          size += com.google.protobuf.CodedOutputStream
            .computeEnumSize(1, brand_);
        }
        if (!getNameBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof com.demo.netty.protobuf.personinfo.pojo.RichManProto.RichMan.Car)) {
          return super.equals(obj);
        }
        com.demo.netty.protobuf.personinfo.pojo.RichManProto.RichMan.Car other = (com.demo.netty.protobuf.personinfo.pojo.RichManProto.RichMan.Car) obj;

        if (brand_ != other.brand_) return false;
        if (!getName()
            .equals(other.getName())) return false;
        if (!unknownFields.equals(other.unknownFields)) return false;
        return true;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + BRAND_FIELD_NUMBER;
        hash = (53 * hash) + brand_;
        hash = (37 * hash) + NAME_FIELD_NUMBER;
        hash = (53 * hash) + getName().hashCode();
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static com.demo.netty.protobuf.personinfo.pojo.RichManProto.RichMan.Car parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.demo.netty.protobuf.personinfo.pojo.RichManProto.RichMan.Car parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.demo.netty.protobuf.personinfo.pojo.RichManProto.RichMan.Car parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.demo.netty.protobuf.personinfo.pojo.RichManProto.RichMan.Car parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.demo.netty.protobuf.personinfo.pojo.RichManProto.RichMan.Car parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.demo.netty.protobuf.personinfo.pojo.RichManProto.RichMan.Car parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.demo.netty.protobuf.personinfo.pojo.RichManProto.RichMan.Car parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static com.demo.netty.protobuf.personinfo.pojo.RichManProto.RichMan.Car parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static com.demo.netty.protobuf.personinfo.pojo.RichManProto.RichMan.Car parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static com.demo.netty.protobuf.personinfo.pojo.RichManProto.RichMan.Car parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static com.demo.netty.protobuf.personinfo.pojo.RichManProto.RichMan.Car parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static com.demo.netty.protobuf.personinfo.pojo.RichManProto.RichMan.Car parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @java.lang.Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(com.demo.netty.protobuf.personinfo.pojo.RichManProto.RichMan.Car prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @java.lang.Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code netty.RichMan.Car}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:netty.RichMan.Car)
          com.demo.netty.protobuf.personinfo.pojo.RichManProto.RichMan.CarOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.demo.netty.protobuf.personinfo.pojo.RichManProto.internal_static_netty_RichMan_Car_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.demo.netty.protobuf.personinfo.pojo.RichManProto.internal_static_netty_RichMan_Car_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  com.demo.netty.protobuf.personinfo.pojo.RichManProto.RichMan.Car.class, com.demo.netty.protobuf.personinfo.pojo.RichManProto.RichMan.Car.Builder.class);
        }

        // Construct using com.demo.netty.protobuf.pojo.RichManProto.RichMan.Car.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        @java.lang.Override
        public Builder clear() {
          super.clear();
          brand_ = 0;

          name_ = "";

          return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.demo.netty.protobuf.personinfo.pojo.RichManProto.internal_static_netty_RichMan_Car_descriptor;
        }

        @java.lang.Override
        public com.demo.netty.protobuf.personinfo.pojo.RichManProto.RichMan.Car getDefaultInstanceForType() {
          return com.demo.netty.protobuf.personinfo.pojo.RichManProto.RichMan.Car.getDefaultInstance();
        }

        @java.lang.Override
        public com.demo.netty.protobuf.personinfo.pojo.RichManProto.RichMan.Car build() {
          com.demo.netty.protobuf.personinfo.pojo.RichManProto.RichMan.Car result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @java.lang.Override
        public com.demo.netty.protobuf.personinfo.pojo.RichManProto.RichMan.Car buildPartial() {
          com.demo.netty.protobuf.personinfo.pojo.RichManProto.RichMan.Car result = new com.demo.netty.protobuf.personinfo.pojo.RichManProto.RichMan.Car(this);
          result.brand_ = brand_;
          result.name_ = name_;
          onBuilt();
          return result;
        }

        @java.lang.Override
        public Builder clone() {
          return super.clone();
        }
        @java.lang.Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.setField(field, value);
        }
        @java.lang.Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return super.clearField(field);
        }
        @java.lang.Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return super.clearOneof(oneof);
        }
        @java.lang.Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return super.setRepeatedField(field, index, value);
        }
        @java.lang.Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.addRepeatedField(field, value);
        }
        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.demo.netty.protobuf.personinfo.pojo.RichManProto.RichMan.Car) {
            return mergeFrom((com.demo.netty.protobuf.personinfo.pojo.RichManProto.RichMan.Car)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(com.demo.netty.protobuf.personinfo.pojo.RichManProto.RichMan.Car other) {
          if (other == com.demo.netty.protobuf.personinfo.pojo.RichManProto.RichMan.Car.getDefaultInstance()) return this;
          if (other.brand_ != 0) {
            setBrandValue(other.getBrandValue());
          }
          if (!other.getName().isEmpty()) {
            name_ = other.name_;
            onChanged();
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
          return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.demo.netty.protobuf.personinfo.pojo.RichManProto.RichMan.Car parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (com.demo.netty.protobuf.personinfo.pojo.RichManProto.RichMan.Car) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }

        private int brand_ = 0;
        /**
         * <code>.netty.RichMan.CarBrand brand = 1;</code>
         */
        public int getBrandValue() {
          return brand_;
        }
        /**
         * <code>.netty.RichMan.CarBrand brand = 1;</code>
         */
        public Builder setBrandValue(int value) {
          brand_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>.netty.RichMan.CarBrand brand = 1;</code>
         */
        public com.demo.netty.protobuf.personinfo.pojo.RichManProto.RichMan.CarBrand getBrand() {
          @SuppressWarnings("deprecation")
          com.demo.netty.protobuf.personinfo.pojo.RichManProto.RichMan.CarBrand result = com.demo.netty.protobuf.personinfo.pojo.RichManProto.RichMan.CarBrand.valueOf(brand_);
          return result == null ? com.demo.netty.protobuf.personinfo.pojo.RichManProto.RichMan.CarBrand.UNRECOGNIZED : result;
        }
        /**
         * <code>.netty.RichMan.CarBrand brand = 1;</code>
         */
        public Builder setBrand(com.demo.netty.protobuf.personinfo.pojo.RichManProto.RichMan.CarBrand value) {
          if (value == null) {
            throw new NullPointerException();
          }
          
          brand_ = value.getNumber();
          onChanged();
          return this;
        }
        /**
         * <code>.netty.RichMan.CarBrand brand = 1;</code>
         */
        public Builder clearBrand() {
          
          brand_ = 0;
          onChanged();
          return this;
        }

        private java.lang.Object name_ = "";
        /**
         * <code>string name = 2;</code>
         */
        public java.lang.String getName() {
          java.lang.Object ref = name_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            name_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>string name = 2;</code>
         */
        public com.google.protobuf.ByteString
            getNameBytes() {
          java.lang.Object ref = name_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            name_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string name = 2;</code>
         */
        public Builder setName(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          name_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>string name = 2;</code>
         */
        public Builder clearName() {
          
          name_ = getDefaultInstance().getName();
          onChanged();
          return this;
        }
        /**
         * <code>string name = 2;</code>
         */
        public Builder setNameBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          name_ = value;
          onChanged();
          return this;
        }
        @java.lang.Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:netty.RichMan.Car)
      }

      // @@protoc_insertion_point(class_scope:netty.RichMan.Car)
      private static final com.demo.netty.protobuf.personinfo.pojo.RichManProto.RichMan.Car DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new com.demo.netty.protobuf.personinfo.pojo.RichManProto.RichMan.Car();
      }

      public static com.demo.netty.protobuf.personinfo.pojo.RichManProto.RichMan.Car getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<Car>
          PARSER = new com.google.protobuf.AbstractParser<Car>() {
        @java.lang.Override
        public Car parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Car(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<Car> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<Car> getParserForType() {
        return PARSER;
      }

      @java.lang.Override
      public com.demo.netty.protobuf.personinfo.pojo.RichManProto.RichMan.Car getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 2;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EMAIL_FIELD_NUMBER = 3;
    private volatile java.lang.Object email_;
    /**
     * <code>string email = 3;</code>
     */
    public java.lang.String getEmail() {
      java.lang.Object ref = email_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        email_ = s;
        return s;
      }
    }
    /**
     * <code>string email = 3;</code>
     */
    public com.google.protobuf.ByteString
        getEmailBytes() {
      java.lang.Object ref = email_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        email_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CARS_FIELD_NUMBER = 4;
    private java.util.List<com.demo.netty.protobuf.personinfo.pojo.RichManProto.RichMan.Car> cars_;
    /**
     * <code>repeated .netty.RichMan.Car cars = 4;</code>
     */
    public java.util.List<com.demo.netty.protobuf.personinfo.pojo.RichManProto.RichMan.Car> getCarsList() {
      return cars_;
    }
    /**
     * <code>repeated .netty.RichMan.Car cars = 4;</code>
     */
    public java.util.List<? extends com.demo.netty.protobuf.personinfo.pojo.RichManProto.RichMan.CarOrBuilder>
        getCarsOrBuilderList() {
      return cars_;
    }
    /**
     * <code>repeated .netty.RichMan.Car cars = 4;</code>
     */
    public int getCarsCount() {
      return cars_.size();
    }
    /**
     * <code>repeated .netty.RichMan.Car cars = 4;</code>
     */
    public com.demo.netty.protobuf.personinfo.pojo.RichManProto.RichMan.Car getCars(int index) {
      return cars_.get(index);
    }
    /**
     * <code>repeated .netty.RichMan.Car cars = 4;</code>
     */
    public com.demo.netty.protobuf.personinfo.pojo.RichManProto.RichMan.CarOrBuilder getCarsOrBuilder(
        int index) {
      return cars_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      if (!getEmailBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, email_);
      }
      for (int i = 0; i < cars_.size(); i++) {
        output.writeMessage(4, cars_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      if (!getEmailBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, email_);
      }
      for (int i = 0; i < cars_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, cars_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.demo.netty.protobuf.personinfo.pojo.RichManProto.RichMan)) {
        return super.equals(obj);
      }
      com.demo.netty.protobuf.personinfo.pojo.RichManProto.RichMan other = (com.demo.netty.protobuf.personinfo.pojo.RichManProto.RichMan) obj;

      if (getId()
          != other.getId()) return false;
      if (!getName()
          .equals(other.getName())) return false;
      if (!getEmail()
          .equals(other.getEmail())) return false;
      if (!getCarsList()
          .equals(other.getCarsList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + EMAIL_FIELD_NUMBER;
      hash = (53 * hash) + getEmail().hashCode();
      if (getCarsCount() > 0) {
        hash = (37 * hash) + CARS_FIELD_NUMBER;
        hash = (53 * hash) + getCarsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.demo.netty.protobuf.personinfo.pojo.RichManProto.RichMan parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.demo.netty.protobuf.personinfo.pojo.RichManProto.RichMan parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.demo.netty.protobuf.personinfo.pojo.RichManProto.RichMan parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.demo.netty.protobuf.personinfo.pojo.RichManProto.RichMan parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.demo.netty.protobuf.personinfo.pojo.RichManProto.RichMan parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.demo.netty.protobuf.personinfo.pojo.RichManProto.RichMan parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.demo.netty.protobuf.personinfo.pojo.RichManProto.RichMan parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.demo.netty.protobuf.personinfo.pojo.RichManProto.RichMan parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.demo.netty.protobuf.personinfo.pojo.RichManProto.RichMan parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.demo.netty.protobuf.personinfo.pojo.RichManProto.RichMan parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.demo.netty.protobuf.personinfo.pojo.RichManProto.RichMan parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.demo.netty.protobuf.personinfo.pojo.RichManProto.RichMan parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.demo.netty.protobuf.personinfo.pojo.RichManProto.RichMan prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code netty.RichMan}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:netty.RichMan)
        com.demo.netty.protobuf.personinfo.pojo.RichManProto.RichManOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.demo.netty.protobuf.personinfo.pojo.RichManProto.internal_static_netty_RichMan_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.demo.netty.protobuf.personinfo.pojo.RichManProto.internal_static_netty_RichMan_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.demo.netty.protobuf.personinfo.pojo.RichManProto.RichMan.class, com.demo.netty.protobuf.personinfo.pojo.RichManProto.RichMan.Builder.class);
      }

      // Construct using com.demo.netty.protobuf.pojo.RichManProto.RichMan.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getCarsFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = 0;

        name_ = "";

        email_ = "";

        if (carsBuilder_ == null) {
          cars_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
        } else {
          carsBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.demo.netty.protobuf.personinfo.pojo.RichManProto.internal_static_netty_RichMan_descriptor;
      }

      @java.lang.Override
      public com.demo.netty.protobuf.personinfo.pojo.RichManProto.RichMan getDefaultInstanceForType() {
        return com.demo.netty.protobuf.personinfo.pojo.RichManProto.RichMan.getDefaultInstance();
      }

      @java.lang.Override
      public com.demo.netty.protobuf.personinfo.pojo.RichManProto.RichMan build() {
        com.demo.netty.protobuf.personinfo.pojo.RichManProto.RichMan result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.demo.netty.protobuf.personinfo.pojo.RichManProto.RichMan buildPartial() {
        com.demo.netty.protobuf.personinfo.pojo.RichManProto.RichMan result = new com.demo.netty.protobuf.personinfo.pojo.RichManProto.RichMan(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.id_ = id_;
        result.name_ = name_;
        result.email_ = email_;
        if (carsBuilder_ == null) {
          if (((bitField0_ & 0x00000008) != 0)) {
            cars_ = java.util.Collections.unmodifiableList(cars_);
            bitField0_ = (bitField0_ & ~0x00000008);
          }
          result.cars_ = cars_;
        } else {
          result.cars_ = carsBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.demo.netty.protobuf.personinfo.pojo.RichManProto.RichMan) {
          return mergeFrom((com.demo.netty.protobuf.personinfo.pojo.RichManProto.RichMan)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.demo.netty.protobuf.personinfo.pojo.RichManProto.RichMan other) {
        if (other == com.demo.netty.protobuf.personinfo.pojo.RichManProto.RichMan.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (!other.getEmail().isEmpty()) {
          email_ = other.email_;
          onChanged();
        }
        if (carsBuilder_ == null) {
          if (!other.cars_.isEmpty()) {
            if (cars_.isEmpty()) {
              cars_ = other.cars_;
              bitField0_ = (bitField0_ & ~0x00000008);
            } else {
              ensureCarsIsMutable();
              cars_.addAll(other.cars_);
            }
            onChanged();
          }
        } else {
          if (!other.cars_.isEmpty()) {
            if (carsBuilder_.isEmpty()) {
              carsBuilder_.dispose();
              carsBuilder_ = null;
              cars_ = other.cars_;
              bitField0_ = (bitField0_ & ~0x00000008);
              carsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getCarsFieldBuilder() : null;
            } else {
              carsBuilder_.addAllMessages(other.cars_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.demo.netty.protobuf.personinfo.pojo.RichManProto.RichMan parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.demo.netty.protobuf.personinfo.pojo.RichManProto.RichMan) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int id_ ;
      /**
       * <code>int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 1;</code>
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 2;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object email_ = "";
      /**
       * <code>string email = 3;</code>
       */
      public java.lang.String getEmail() {
        java.lang.Object ref = email_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          email_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string email = 3;</code>
       */
      public com.google.protobuf.ByteString
          getEmailBytes() {
        java.lang.Object ref = email_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          email_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string email = 3;</code>
       */
      public Builder setEmail(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        email_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string email = 3;</code>
       */
      public Builder clearEmail() {
        
        email_ = getDefaultInstance().getEmail();
        onChanged();
        return this;
      }
      /**
       * <code>string email = 3;</code>
       */
      public Builder setEmailBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        email_ = value;
        onChanged();
        return this;
      }

      private java.util.List<com.demo.netty.protobuf.personinfo.pojo.RichManProto.RichMan.Car> cars_ =
        java.util.Collections.emptyList();
      private void ensureCarsIsMutable() {
        if (!((bitField0_ & 0x00000008) != 0)) {
          cars_ = new java.util.ArrayList<com.demo.netty.protobuf.personinfo.pojo.RichManProto.RichMan.Car>(cars_);
          bitField0_ |= 0x00000008;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.demo.netty.protobuf.personinfo.pojo.RichManProto.RichMan.Car, com.demo.netty.protobuf.personinfo.pojo.RichManProto.RichMan.Car.Builder, com.demo.netty.protobuf.personinfo.pojo.RichManProto.RichMan.CarOrBuilder> carsBuilder_;

      /**
       * <code>repeated .netty.RichMan.Car cars = 4;</code>
       */
      public java.util.List<com.demo.netty.protobuf.personinfo.pojo.RichManProto.RichMan.Car> getCarsList() {
        if (carsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(cars_);
        } else {
          return carsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .netty.RichMan.Car cars = 4;</code>
       */
      public int getCarsCount() {
        if (carsBuilder_ == null) {
          return cars_.size();
        } else {
          return carsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .netty.RichMan.Car cars = 4;</code>
       */
      public com.demo.netty.protobuf.personinfo.pojo.RichManProto.RichMan.Car getCars(int index) {
        if (carsBuilder_ == null) {
          return cars_.get(index);
        } else {
          return carsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .netty.RichMan.Car cars = 4;</code>
       */
      public Builder setCars(
          int index, com.demo.netty.protobuf.personinfo.pojo.RichManProto.RichMan.Car value) {
        if (carsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCarsIsMutable();
          cars_.set(index, value);
          onChanged();
        } else {
          carsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .netty.RichMan.Car cars = 4;</code>
       */
      public Builder setCars(
          int index, com.demo.netty.protobuf.personinfo.pojo.RichManProto.RichMan.Car.Builder builderForValue) {
        if (carsBuilder_ == null) {
          ensureCarsIsMutable();
          cars_.set(index, builderForValue.build());
          onChanged();
        } else {
          carsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .netty.RichMan.Car cars = 4;</code>
       */
      public Builder addCars(com.demo.netty.protobuf.personinfo.pojo.RichManProto.RichMan.Car value) {
        if (carsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCarsIsMutable();
          cars_.add(value);
          onChanged();
        } else {
          carsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .netty.RichMan.Car cars = 4;</code>
       */
      public Builder addCars(
          int index, com.demo.netty.protobuf.personinfo.pojo.RichManProto.RichMan.Car value) {
        if (carsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCarsIsMutable();
          cars_.add(index, value);
          onChanged();
        } else {
          carsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .netty.RichMan.Car cars = 4;</code>
       */
      public Builder addCars(
          com.demo.netty.protobuf.personinfo.pojo.RichManProto.RichMan.Car.Builder builderForValue) {
        if (carsBuilder_ == null) {
          ensureCarsIsMutable();
          cars_.add(builderForValue.build());
          onChanged();
        } else {
          carsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .netty.RichMan.Car cars = 4;</code>
       */
      public Builder addCars(
          int index, com.demo.netty.protobuf.personinfo.pojo.RichManProto.RichMan.Car.Builder builderForValue) {
        if (carsBuilder_ == null) {
          ensureCarsIsMutable();
          cars_.add(index, builderForValue.build());
          onChanged();
        } else {
          carsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .netty.RichMan.Car cars = 4;</code>
       */
      public Builder addAllCars(
          java.lang.Iterable<? extends com.demo.netty.protobuf.personinfo.pojo.RichManProto.RichMan.Car> values) {
        if (carsBuilder_ == null) {
          ensureCarsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, cars_);
          onChanged();
        } else {
          carsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .netty.RichMan.Car cars = 4;</code>
       */
      public Builder clearCars() {
        if (carsBuilder_ == null) {
          cars_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
          onChanged();
        } else {
          carsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .netty.RichMan.Car cars = 4;</code>
       */
      public Builder removeCars(int index) {
        if (carsBuilder_ == null) {
          ensureCarsIsMutable();
          cars_.remove(index);
          onChanged();
        } else {
          carsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .netty.RichMan.Car cars = 4;</code>
       */
      public com.demo.netty.protobuf.personinfo.pojo.RichManProto.RichMan.Car.Builder getCarsBuilder(
          int index) {
        return getCarsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .netty.RichMan.Car cars = 4;</code>
       */
      public com.demo.netty.protobuf.personinfo.pojo.RichManProto.RichMan.CarOrBuilder getCarsOrBuilder(
          int index) {
        if (carsBuilder_ == null) {
          return cars_.get(index);  } else {
          return carsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .netty.RichMan.Car cars = 4;</code>
       */
      public java.util.List<? extends com.demo.netty.protobuf.personinfo.pojo.RichManProto.RichMan.CarOrBuilder>
           getCarsOrBuilderList() {
        if (carsBuilder_ != null) {
          return carsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(cars_);
        }
      }
      /**
       * <code>repeated .netty.RichMan.Car cars = 4;</code>
       */
      public com.demo.netty.protobuf.personinfo.pojo.RichManProto.RichMan.Car.Builder addCarsBuilder() {
        return getCarsFieldBuilder().addBuilder(
            com.demo.netty.protobuf.personinfo.pojo.RichManProto.RichMan.Car.getDefaultInstance());
      }
      /**
       * <code>repeated .netty.RichMan.Car cars = 4;</code>
       */
      public com.demo.netty.protobuf.personinfo.pojo.RichManProto.RichMan.Car.Builder addCarsBuilder(
          int index) {
        return getCarsFieldBuilder().addBuilder(
            index, com.demo.netty.protobuf.personinfo.pojo.RichManProto.RichMan.Car.getDefaultInstance());
      }
      /**
       * <code>repeated .netty.RichMan.Car cars = 4;</code>
       */
      public java.util.List<com.demo.netty.protobuf.personinfo.pojo.RichManProto.RichMan.Car.Builder>
           getCarsBuilderList() {
        return getCarsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.demo.netty.protobuf.personinfo.pojo.RichManProto.RichMan.Car, com.demo.netty.protobuf.personinfo.pojo.RichManProto.RichMan.Car.Builder, com.demo.netty.protobuf.personinfo.pojo.RichManProto.RichMan.CarOrBuilder>
          getCarsFieldBuilder() {
        if (carsBuilder_ == null) {
          carsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.demo.netty.protobuf.personinfo.pojo.RichManProto.RichMan.Car, com.demo.netty.protobuf.personinfo.pojo.RichManProto.RichMan.Car.Builder, com.demo.netty.protobuf.personinfo.pojo.RichManProto.RichMan.CarOrBuilder>(
                  cars_,
                  ((bitField0_ & 0x00000008) != 0),
                  getParentForChildren(),
                  isClean());
          cars_ = null;
        }
        return carsBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:netty.RichMan)
    }

    // @@protoc_insertion_point(class_scope:netty.RichMan)
    private static final com.demo.netty.protobuf.personinfo.pojo.RichManProto.RichMan DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.demo.netty.protobuf.personinfo.pojo.RichManProto.RichMan();
    }

    public static com.demo.netty.protobuf.personinfo.pojo.RichManProto.RichMan getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RichMan>
        PARSER = new com.google.protobuf.AbstractParser<RichMan>() {
      @java.lang.Override
      public RichMan parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RichMan(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<RichMan> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RichMan> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.demo.netty.protobuf.personinfo.pojo.RichManProto.RichMan getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_netty_RichMan_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_netty_RichMan_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_netty_RichMan_Car_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_netty_RichMan_Car_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rRichMan.proto\022\005netty\"\317\001\n\007RichMan\022\n\n\002id" +
      "\030\001 \001(\005\022\014\n\004name\030\002 \001(\t\022\r\n\005email\030\003 \001(\t\022 \n\004c" +
      "ars\030\004 \003(\0132\022.netty.RichMan.Car\032;\n\003Car\022&\n\005" +
      "brand\030\001 \001(\0162\027.netty.RichMan.CarBrand\022\014\n\004" +
      "name\030\002 \001(\t\"<\n\010CarBrand\022\010\n\004BENZ\020\000\022\017\n\013LAMB" +
      "ORGHINI\020\001\022\013\n\007PORSCHE\020\002\022\010\n\004AUQI\020\003B,\n\034com." +
      "demo.netty.protobuf.pojoB\014RichManProtob\006" +
      "proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_netty_RichMan_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_netty_RichMan_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_netty_RichMan_descriptor,
        new java.lang.String[] { "Id", "Name", "Email", "Cars", });
    internal_static_netty_RichMan_Car_descriptor =
      internal_static_netty_RichMan_descriptor.getNestedTypes().get(0);
    internal_static_netty_RichMan_Car_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_netty_RichMan_Car_descriptor,
        new java.lang.String[] { "Brand", "Name", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
